MiContaSoporteBundle_admin_javier_soporte_bundle_Perfil:
    resource: "@MiContaSoporteBundle/Controller/Perfil/"
    type:     admingenerator
    prefix:   /admin/perfil/
    
menu_perfil:
    path: /admin/perfil/menus/{pk}/
    defaults: {_controller: "MiContaSoporteBundle:Perfil:menu"}

MiContaSoporteBundle_admin_javier_soporte_bundle_Usuario:
    resource: "@MiContaSoporteBundle/Controller/Usuario/"
    type:     admingenerator
    prefix:   /admin/usuario/
    
editar_perfiles_usuario:
    path: /admin/usuario/perfil/
    defaults: { _controller: MiContaSoporteBundle:Usuario:editarPerfil }
    
usuario_perfil:
    path: /usuario/perfil/
    defaults: {_controller: MiContaSoporteBundle:Usuario:perfil}