mi_conta_cuenta:
    resource: "@MiContaCuentaBundle/Resources/config/routing.yml"
    prefix:   /

gea_soporte:
    resource: "@MiContaSoporteBundle/Resources/config/routing.yml"
    prefix:   /soporte/
    
pagina_inicio:
    path:    /
    defaults: { _controller: MiContaSoporteBundle:Default:portada }
_pagina_inicio:
    path:    /inicio/
    defaults: { _controller: MiContaSoporteBundle:Default:portada }
    
#Autenticacion y salida
usuario_logout:
    path: /usuario/logout/
usuario_login:
    path: /usuario/login
    defaults: { _controller: MiContaSoporteBundle:Login:login }
usuario_pre_logout:
    path: /usuario/pre/logout/
    defaults: { _controller: MiContaSoporteBundle:Login:preLogout }